"""Document metadata *values* are prose until a naming key says otherwise.

Regression: `AI_META_NAME_RE` -- a vocabulary built to match metadata *names*
-- was matched against every frontmatter value as a bare substring. Ordinary
English then read as provenance: a note whose `context:` field said "a
generator produced 29 datasheets" hit on the word "generator".

In `check` mode that is a false warning. In `clean` mode the cleaner drops the
whole key *and every nested line under it*, so an author's own text is deleted
because they wrote a common noun. The file still parses afterwards, so nothing
downstream notices.

The rule restored here is the project's existing one, applied to Markdown:
image_meta scans values for product names only under naming keys
(Software/Creator/parameters) and matches unkeyed JPEG COM text against
unambiguous markers alone, precisely because "Claude Monet" and "Generated by
ImageMagick" are ordinary prose.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "service" / "scripts"
sys.path.insert(0, str(SCRIPTS))

from container_meta import (
    _meta_tag_is_ai,
    clean_html,
    clean_markdown,
    inspect_html,
    inspect_markdown,
    named_value_is_ai,
)

# Prose an author legitimately writes about their own subject. Every one of
# these contains a word from the *name* vocabulary and none is a provenance
# mark. Drawn from real documents: engineering notes, changelogs, docs about
# provenance tooling itself.
PROSE_VALUES = [
    "A generator produced 29 branded PDF datasheets, each stamped with a code.",
    "Binds where artefacts are cached (they run generators and gates)",
    "How to build a static site generator in Rust",
    "Notes on content provenance standards and their tradeoffs",
    "The digital source of the figures is the 2026 price list",
    "Claude Monet, water lilies, 1906",
    "Comparing OpenAI and Gemini pricing for the procurement review",
    "Why our AI generated captions needed a human pass",
]


def _doc(key: str, value: str) -> str:
    return f"---\ntitle: Demo\n{key}: {value}\nauthor: you\n---\nBody\n"


@pytest.mark.parametrize("value", PROSE_VALUES)
def test_prose_value_under_a_plain_key_is_not_flagged(value: str) -> None:
    _c2, has_ai, findings, _d = inspect_markdown(_doc("context", value))
    assert not has_ai, findings


@pytest.mark.parametrize("value", PROSE_VALUES)
def test_prose_value_survives_clean(value: str) -> None:
    """The destructive half: clean must not delete the author's own text."""
    cleaned, _actions = clean_markdown(_doc("context", value))
    assert value in cleaned
    assert "context:" in cleaned


def test_nested_block_under_a_prose_key_survives_clean() -> None:
    """A value hit drops nested children too, so the blast radius is bigger."""
    text = (
        "---\n"
        "title: Demo\n"
        "context: A generator produced the cards\n"
        "steps:\n"
        "  - measure\n"
        "  - verify\n"
        "---\n"
        "Body\n"
    )
    cleaned, _ = clean_markdown(text)
    assert "- measure" in cleaned
    assert "- verify" in cleaned
    assert "A generator produced the cards" in cleaned


# --- what must STILL be caught -------------------------------------------


@pytest.mark.parametrize(
    "key,value",
    [
        ("generator", "Claude"),
        ("generated_by", "Gemini"),
        ("created_with", "Anthropic Claude 3.5 Sonnet"),
        ("tool", "Gemini"),
        ("software", "OpenAI ChatGPT"),
        ("producer", "SynthID"),
    ],
)
def test_naming_key_with_a_vendor_value_is_still_flagged(key: str, value: str) -> None:
    _c2, has_ai, _f, _d = inspect_markdown(_doc(key, value))
    assert has_ai, f"{key}: {value} should read as provenance"
    cleaned, actions = clean_markdown(_doc(key, value))
    assert f"{key}:" not in cleaned
    assert any("drop" in a for a in actions)
    assert "title: Demo" in cleaned  # siblings untouched
    assert "author: you" in cleaned


@pytest.mark.parametrize(
    "value",
    [
        "c2pa manifest attached",
        "Content-Credentials embedded at export",
        "digitalSourceType: trainedAlgorithmicMedia",
        "SynthID watermark present",
        "aigc",
    ],
)
def test_unambiguous_marker_is_flagged_even_under_a_plain_key(value: str) -> None:
    """Markers that are never ordinary English stay in scope everywhere."""
    _c2, has_ai, findings, _d = inspect_markdown(_doc("note", value))
    assert has_ai, findings


@pytest.mark.parametrize("value", ["GPT-4o", "ChatGPT", "Midjourney", "DALL-E"])
def test_product_names_under_naming_keys_are_out_of_scope_today(value: str) -> None:
    """Pins a pre-existing gap, unchanged by this fix, so it stays visible.

    AI_META_NAME_RE lists vendors (claude, openai, gemini, ...) but not the
    product names a tool actually writes -- image_meta got those in #120 via
    AI_GENERATOR_PRODUCTS, Markdown never did. So `generated_by: GPT-4o` reads
    clean, before this change and after it. Widening the vocabulary is a
    separate change; this test fails the day someone makes it, which is the
    point.
    """
    assert not named_value_is_ai("generated_by", value)


@pytest.mark.parametrize("value", ["aigcorp", "raigcode", "c2pattern"])
def test_markers_are_word_anchored(value: str) -> None:
    """Unanchored alternation matched 'aigc' inside unrelated words."""
    assert not named_value_is_ai("note", value)


# --- the two paths may never disagree ------------------------------------


@pytest.mark.parametrize(
    "key,value",
    [(k, v) for k in ("context", "generator", "note", "tool") for v in PROSE_VALUES]
    + [("generator", "Claude"), ("note", "c2pa manifest"), ("tool", "Gemini")],
)
def test_inspect_and_clean_agree(key: str, value: str) -> None:
    """A checker and the cleaner it gates must decide identically.

    They read the same helper now; this pins that they keep doing so. If they
    drift, `check` reports a file clean while `clean` silently deletes a key
    from it -- the failure mode this whole class of bug produces.
    """
    doc = _doc(key, value)
    flagged = named_value_is_ai(key, value)
    key_is_ai_by_name = f"frontmatter key: {key}" in inspect_markdown(doc)[2]

    cleaned, _ = clean_markdown(doc)
    dropped = f"{key}:" not in cleaned

    assert dropped == (flagged or key_is_ai_by_name)


def test_cleaned_output_is_no_longer_flagged() -> None:
    """Round-trip: whatever clean leaves behind must inspect clean."""
    text = _doc("generator", "Claude")
    cleaned, _ = clean_markdown(text)
    _c2, has_ai, findings, _d = inspect_markdown(cleaned)
    assert not has_ai, findings


# --- the same defect in HTML <meta content="..."> ------------------------


def _page(name: str, content: str) -> str:
    return (
        "<html><head><title>T</title>"
        f'<meta name="{name}" content="{content}">'
        "</head><body><p>Body</p></body></html>"
    )


@pytest.mark.parametrize("value", PROSE_VALUES)
def test_meta_description_prose_is_not_flagged(value: str) -> None:
    _c2, has_ai, findings, _d = inspect_html(_page("description", value))
    assert not has_ai, findings


@pytest.mark.parametrize("value", PROSE_VALUES)
def test_meta_description_survives_clean(value: str) -> None:
    """A page must not lose its description to a sentence about generators."""
    cleaned, _ = clean_html(_page("description", value))
    assert value in cleaned


def test_ai_generator_meta_is_still_dropped() -> None:
    page = _page("generator", "Claude")
    _c2, has_ai, findings, _d = inspect_html(page)
    assert has_ai, findings
    cleaned, actions = clean_html(page)
    assert "Claude" not in cleaned
    assert any("drop meta" in a for a in actions)


def test_cms_generator_meta_is_still_kept() -> None:
    """WordPress is CMS provenance, not AI provenance -- unchanged."""
    page = _page("generator", "WordPress 6.5")
    _c2, has_ai, _f, _d = inspect_html(page)
    assert not has_ai
    cleaned, _ = clean_html(page)
    assert "WordPress 6.5" in cleaned


def test_unambiguous_marker_in_meta_content_is_still_flagged() -> None:
    page = _page("description", "Exported with a C2PA manifest")
    _c2, has_ai, findings, _d = inspect_html(page)
    assert has_ai, findings


@pytest.mark.parametrize(
    "tag",
    [
        # The same string in `content` and in another attribute: blanking the
        # value with str.replace erases both copies, and the tag reads clean.
        '<meta property="Claude" content="Claude">',
        '<meta itemprop="Anthropic" content="Anthropic">',
        '<meta name="synthid" content="synthid">',
        # A marker in an attribute the name parser does not read at all.
        '<meta itemprop="c2pa" content="a note about cards">',
        # Unquoted content attribute -- falls back to the whole-tag scan.
        "<meta name=x content=Claude>",
    ],
)
def test_marker_outside_content_attribute_is_still_flagged(tag: str) -> None:
    """Only `content` gets the prose rule; other attributes keep the old scan.

    The first version of this test carried a `data-ai-generated` attribute as
    well, so it passed through inspect_html's separate data-ai* branch and
    proved nothing about the split it was named for.
    """
    assert _meta_tag_is_ai(tag), tag
    page = f"<html><head>{tag}</head><body>x</body></html>"
    _c2, has_ai, findings, _d = inspect_html(page)
    assert has_ai, findings


def test_html_inspect_and_clean_agree() -> None:
    """inspect and clean must not disagree about any tag in the corpus."""
    for name in ("description", "generator", "og:description", "author"):
        for value in [*PROSE_VALUES, "Claude", "C2PA manifest", "WordPress 6.5"]:
            page = _page(name, value)
            _c2, has_ai, _f, _d = inspect_html(page)
            cleaned, _ = clean_html(page)
            dropped = value not in cleaned
            if dropped:
                assert has_ai, f"clean dropped {name}={value!r} but inspect called it clean"
