import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "service" / "scripts"
sys.path.insert(0, str(SCRIPTS))

import av_meta


def _truncated_id3v2_mp3() -> bytes:
    # ID3v2.3 tag header: "ID3", major=3, revision=0, flags=0, size=500 bytes (synchsafe: [0, 0, 0x03, 0x74])
    # Total tag length declared = 10 + 500 = 510 bytes.
    # We only supply 50 bytes total:
    header = b"ID3\x03\x00\x00\x00\x00\x03\x74"
    partial_payload = b"COMM\x00\x00\x00\x10\x00\x00\x00engGenerated by ChatGPT"
    return header + partial_payload


def test_inspect_truncated_id3v2_reports_finding():
    data = _truncated_id3v2_mp3()
    has_c2pa, has_ai, findings = av_meta._inspect_id3v2(data)
    assert has_ai is True
    assert has_c2pa is False
    assert len(findings) > 0
    assert any("truncated" in f.lower() and "id3" in f.lower() for f in findings)


def test_inspect_truncated_id3v2_without_ai_markers_does_not_claim_ai():
    # ID3v2.3 tag header: declared 500 bytes, only 30 bytes of non-AI audio data present
    header = b"ID3\x03\x00\x00\x00\x00\x03\x74"
    partial_payload = b"TIT2\x00\x00\x00\x0a\x00\x00\x00Track 01"
    data = header + partial_payload
    has_c2pa, has_ai, findings = av_meta._inspect_id3v2(data)
    assert has_ai is False
    assert has_c2pa is False
    assert any("truncated" in f.lower() for f in findings)


def test_strip_truncated_id3v2_without_audio_preserves_file():
    data = _truncated_id3v2_mp3()
    cleaned, actions = av_meta._strip_id3v2(data, strip_all_metadata=True)
    # When no audio frame can be identified, the file must be preserved rather than wiped
    assert cleaned == data
    assert any("preserving file" in a.lower() for a in actions)


def test_strip_truncated_id3v2_drops_tag_and_preserves_valid_audio_tail():
    # MPEG-1 Layer III, 128 kbps, 44.1 kHz: \xff\xfb\x90\x64
    valid_frame = b"\xff\xfb\x90\x64" + (b"\xaa" * 100)
    data = _truncated_id3v2_mp3() + valid_frame
    cleaned, actions = av_meta._strip_id3v2(data, strip_all_metadata=True)
    assert cleaned == valid_frame
    assert any("found audio frame" in a.lower() for a in actions)


def test_strip_truncated_id3v2_rejects_false_sync_before_valid_frame():
    # False sync (\xff\xe0\x00\x00 has reserved layer 00) followed by valid frame
    false_sync = b"\xff\xe0\x00\x00garbage"
    valid_frame = b"\xff\xfb\x90\x64" + (b"\xbb" * 100)
    data = _truncated_id3v2_mp3() + false_sync + valid_frame
    cleaned, actions = av_meta._strip_id3v2(data, strip_all_metadata=True)
    # Must skip false sync and cut cleanly at the real audio frame
    assert cleaned == valid_frame
    assert any("found audio frame" in a.lower() for a in actions)
