"""Unit tests for gui/core.py — the pure-logic layer of the AI watermark GUI.

These tests are written directly against the public contract documented in
gui/SPEC.md, sections "core.py 公开契约" and "测试规格". They intentionally do
not import gui/app.py (see test_app_smoke.py for that) and do not read
core.py's implementation to shape assertions — the contract in SPEC.md is the
only source of truth. All fixtures are generated on the fly in a tempdir; no
binary fixtures are committed to the repo.

If gui/core.py does not exist yet (e.g. a parallel implementation task is
still in flight), the module-level `import core` below raises ImportError and
every test in this file errors out. That is expected and fine: this file must
still pass `python3 -m py_compile`, and once core.py exists with the
documented contract, these tests should pass unmodified.

Run with:
    cd ~/watermarks-remover && python3 -m unittest discover -s gui/tests -v
"""

from __future__ import annotations

import hashlib
import random
import struct
import sys
import unittest
import zlib
from pathlib import Path
from tempfile import TemporaryDirectory

GUI_DIR = Path(__file__).resolve().parent.parent
if str(GUI_DIR) not in sys.path:
    sys.path.insert(0, str(GUI_DIR))

import core  # noqa: E402  (must follow the sys.path shim above)


# ---------------------------------------------------------------------------
# Shared fixture helpers
#
# Every fixture is built fresh, in a per-test tempdir, from first principles
# (raw bytes / raw text) - no binary blobs are read from disk or checked into
# the repo, per SPEC.md's instruction that fixtures live only in tempdir.
#
# All zero-width / invisible codepoints below are written as explicit
# \uXXXX escapes (never as literal invisible characters pasted into this
# source file) so the exact codepoints used are unambiguous on inspection.
# ---------------------------------------------------------------------------

ZERO_WIDTH_CHARS = (chr(0x200B), chr(0x2060), chr(0xFEFF))  # ZWSP, WORD JOINER, ZWNBSP/BOM

PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"


def sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_zero_width_markdown(path: Path) -> str:
    """Write a .md fixture mixing U+200B / U+2060 / U+FEFF into ordinary
    Chinese/English prose (no frontmatter, no code fences).

    Returns the *visible* text: the same content with every injected
    zero-width character removed, i.e. exactly what a correct cleaner should
    produce as output (this repo's markdown cleaner does not otherwise touch
    plain paragraph text -- no frontmatter or embedded data URIs are present
    in this fixture).
    """
    visible_parts = [
        "# 测试文档\n\n这是一段正常的中文测试文本，用来验证隐藏水印检测功能是否正常工作。\n",
        "This is a normal English sentence mixed in for good measure.\n",
        "再来一句中文收尾，用来确认清理后可见文字完全不变。\n",
    ]
    raw = (
        visible_parts[0]
        + chr(0x200B) * 2
        + visible_parts[1]
        + chr(0x2060)
        + visible_parts[2]
        + chr(0xFEFF)
    )
    path.write_text(raw, encoding="utf-8")
    return "".join(visible_parts)


def write_clean_txt(path: Path) -> str:
    text = (
        "这是一份完全干净的文本文件，没有任何隐藏字符或水印痕迹。\n"
        "Just plain, boring ASCII and CJK text with nothing suspicious in it.\n"
    )
    path.write_text(text, encoding="utf-8")
    return text


def _crc32_bytes(ctype: bytes, payload: bytes) -> bytes:
    return struct.pack(">I", zlib.crc32(ctype + payload) & 0xFFFFFFFF)


def _png_chunk(ctype: bytes, payload: bytes) -> bytes:
    return struct.pack(">I", len(payload)) + ctype + payload + _crc32_bytes(ctype, payload)


def build_minimal_png(with_text_chunk: bool = True) -> bytes:
    """Hand-build a minimal, spec-legal 1x1 8-bit grayscale PNG:
    signature + IHDR + (tEXt) + IDAT + IEND, with correct chunk CRCs.

    When with_text_chunk is True, the tEXt chunk's value contains an
    AI-provenance phrase ("Generated by ...") that this repo's PNG inspector
    recognizes as an AI/provenance hint, without also containing a
    C2PA-specific marker -- so the fixture should scan as actionable via
    generic image-metadata detection, not specifically the C2PA branch.
    """
    ihdr_payload = struct.pack(">IIBBBBB", 1, 1, 8, 0, 0, 0, 0)  # 1x1 px, 8-bit, grayscale
    raw_scanline = bytes([0, 0])  # filter-type byte (0=None) + one gray pixel
    idat_payload = zlib.compress(raw_scanline)

    parts = [PNG_SIGNATURE, _png_chunk(b"IHDR", ihdr_payload)]
    if with_text_chunk:
        text_payload = b"Comment\x00Generated by an AI image tool, for testing purposes only."
        parts.append(_png_chunk(b"tEXt", text_payload))
    parts.append(_png_chunk(b"IDAT", idat_payload))
    parts.append(_png_chunk(b"IEND", b""))
    return b"".join(parts)


def parse_png_chunks(data: bytes) -> list[tuple[bytes, bytes]]:
    """Parse PNG bytes into a list of (chunk_type, payload) tuples, asserting
    along the way that the file is structurally legal: correct signature,
    IHDR first with unmodified 1x1 dimensions, every chunk's CRC32 correct,
    and IEND present as the last chunk.

    Used both to validate our own fixture and to validate a cleaned PNG that
    core.clean_file() produced.
    """
    assert data[:8] == PNG_SIGNATURE, "missing/invalid PNG signature"
    pos = 8
    chunks: list[tuple[bytes, bytes]] = []
    while pos + 8 <= len(data):
        length = struct.unpack(">I", data[pos : pos + 4])[0]
        ctype = data[pos + 4 : pos + 8]
        payload_start = pos + 8
        payload_end = payload_start + length
        payload = data[payload_start:payload_end]
        crc_bytes = data[payload_end : payload_end + 4]
        assert len(crc_bytes) == 4, f"truncated chunk {ctype!r}"
        assert crc_bytes == _crc32_bytes(ctype, payload), f"bad CRC32 for chunk {ctype!r}"
        chunks.append((ctype, payload))
        pos = payload_end + 4
        if ctype == b"IEND":
            break
    assert chunks, "no chunks parsed"
    assert chunks[0][0] == b"IHDR", "IHDR must be the first chunk"
    assert chunks[0][1][:8] == struct.pack(">II", 1, 1), "IHDR pixel dimensions changed"
    assert chunks[-1][0] == b"IEND", "IEND must be the last chunk"
    return chunks


# Magic-byte prefixes recognized by this repo's format sniffer (images,
# zip-based containers, PDF). The unknown-format fixture must not collide
# with any of these by chance.
_KNOWN_MAGIC_PREFIXES = (
    PNG_SIGNATURE,
    b"\xff\xd8",  # JPEG
    b"RIFF",  # WebP/AVI container
    b"BM",  # BMP
    b"GIF87a",
    b"GIF89a",
    b"II*\x00",  # TIFF little-endian
    b"MM\x00*",  # TIFF big-endian
    b"II+\x00",  # BigTIFF little-endian
    b"MM\x00+",  # BigTIFF big-endian
    b"PK\x03\x04",  # zip-based containers (docx/xlsx/pptx/odt/epub)
    b"%PDF",
)


def write_random_bytes_file(path: Path, size: int = 256) -> bytes:
    """Write a .xyz fixture of random bytes, deterministic but re-rolled
    (via an incrementing seed) until it does not start with any magic byte
    sequence this repo's classifier would recognize as a known format.
    """
    seed = 0xBADC0DE
    while True:
        data = bytes(random.Random(seed).getrandbits(8) for _ in range(size))
        if not any(data.startswith(prefix) for prefix in _KNOWN_MAGIC_PREFIXES):
            break
        seed += 1
    path.write_bytes(data)
    return data


class TempDirTestCase(unittest.TestCase):
    """Common tempdir setup shared by the fixture-based test cases below."""

    def setUp(self) -> None:
        self._tmp = TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.tmp_path = Path(self._tmp.name)


# ---------------------------------------------------------------------------
# Contract sanity (not one of the 7 numbered SPEC items, but part of the
# public contract in "core.py 公开契约"; cheap to check so we do).
# ---------------------------------------------------------------------------


class TestModuleContract(unittest.TestCase):
    def test_repo_root_and_scripts_dir(self) -> None:
        self.assertTrue(core.REPO_ROOT.is_dir())
        self.assertEqual(core.SCRIPTS_DIR, core.REPO_ROOT / "service" / "scripts")
        self.assertTrue(core.SCRIPTS_DIR.is_dir())

    def test_tool_hints_returns_list_of_strings(self) -> None:
        hints = core.tool_hints()
        self.assertIsInstance(hints, list)
        for hint in hints:
            self.assertIsInstance(hint, str)


# ---------------------------------------------------------------------------
# SPEC item 1: zero-width characters in a .md file
# ---------------------------------------------------------------------------


class TestZeroWidthMarkdown(TempDirTestCase):
    def setUp(self) -> None:
        super().setUp()
        self.md_path = self.tmp_path / "note.md"
        self.visible_text = write_zero_width_markdown(self.md_path)
        self.original_hash = sha256_of(self.md_path)

    def test_scan_detects_zero_width_characters(self) -> None:
        result = core.scan_file(self.md_path)
        self.assertIsNone(result.error)
        self.assertIsInstance(result.path, Path)
        self.assertTrue(result.actionable)
        self.assertTrue(result.findings, "expected at least one finding")
        self.assertTrue(
            any("隐形字符" in f for f in result.findings),
            f"expected a finding mentioning 隐形字符 (SPEC rule 6), got: {result.findings}",
        )
        # The exact kind label is upstream-defined (SPEC only gives examples);
        # we only require it identifies a real, recognized format.
        self.assertNotEqual(result.kind, "unknown")

    def test_clean_strips_zero_width_and_preserves_visible_text(self) -> None:
        result = core.clean_file(self.md_path)
        self.assertTrue(result.ok, result.message)
        self.assertIsNotNone(result.output)
        assert result.output is not None  # narrows type for the checks below
        self.assertTrue(result.output.exists())
        self.assertEqual(result.output.name, "note_已清理.md")

        cleaned_text = result.output.read_text(encoding="utf-8")
        for ch in ZERO_WIDTH_CHARS:
            self.assertNotIn(ch, cleaned_text, f"zero-width char {ch!r} survived cleaning")
        self.assertEqual(cleaned_text, self.visible_text)

    def test_clean_does_not_modify_original_file(self) -> None:
        core.clean_file(self.md_path)
        self.assertEqual(sha256_of(self.md_path), self.original_hash)


# ---------------------------------------------------------------------------
# SPEC item 2: a clean .txt file
# ---------------------------------------------------------------------------


class TestCleanTextFile(TempDirTestCase):
    def setUp(self) -> None:
        super().setUp()
        self.txt_path = self.tmp_path / "plain.txt"
        write_clean_txt(self.txt_path)
        self.original_hash = sha256_of(self.txt_path)

    def test_scan_reports_not_actionable(self) -> None:
        result = core.scan_file(self.txt_path)
        self.assertIsNone(result.error)
        self.assertFalse(result.actionable)
        self.assertEqual(result.findings, [])
        self.assertEqual(result.kind, "text")

    def test_clean_matches_spec_recommended_behavior(self) -> None:
        # SPEC rule 7's recommended (and here, asserted) behavior for an
        # already-clean file: write no output file, ok=True, and a Chinese
        # message explaining the file was already clean.
        result = core.clean_file(self.txt_path)
        self.assertTrue(result.ok, result.message)
        self.assertIsNone(result.output)
        self.assertIn("干净", result.message)

    def test_clean_does_not_modify_original_file(self) -> None:
        core.clean_file(self.txt_path)
        self.assertEqual(sha256_of(self.txt_path), self.original_hash)


# ---------------------------------------------------------------------------
# SPEC item 3: PNG with a tEXt metadata chunk
# ---------------------------------------------------------------------------


class TestPngTextChunk(TempDirTestCase):
    def setUp(self) -> None:
        super().setUp()
        self.png_path = self.tmp_path / "image.png"
        png_bytes = build_minimal_png(with_text_chunk=True)
        # Sanity-check our own fixture before handing it to core.py: a parse
        # failure here would be a bug in the test, not the implementation.
        fixture_chunks = parse_png_chunks(png_bytes)
        self.assertIn(b"tEXt", [ctype for ctype, _ in fixture_chunks])
        self.png_path.write_bytes(png_bytes)
        self.original_hash = sha256_of(self.png_path)

    def test_scan_detects_text_chunk_metadata(self) -> None:
        result = core.scan_file(self.png_path)
        self.assertIsNone(result.error)
        self.assertTrue(result.actionable)
        self.assertTrue(result.findings)
        # SPEC rule 6 buckets image-metadata findings as either the generic
        # "EXIF/XMP 元数据" category or, if the implementation treats our
        # AI-provenance phrase as a C2PA-adjacent signal, "C2PA 内容凭证".
        # Both are legal per rule 6; we accept either.
        self.assertTrue(
            any(("元数据" in f) or ("C2PA" in f) for f in result.findings),
            f"expected a metadata/C2PA finding, got: {result.findings}",
        )

    def test_clean_strips_text_chunk_and_stays_valid_png(self) -> None:
        result = core.clean_file(self.png_path)
        self.assertTrue(result.ok, result.message)
        self.assertIsNotNone(result.output)
        assert result.output is not None
        self.assertTrue(result.output.exists())
        self.assertEqual(result.output.name, "image_已清理.png")

        cleaned_bytes = result.output.read_bytes()
        chunks = parse_png_chunks(cleaned_bytes)  # raises AssertionError if malformed
        chunk_types = [ctype for ctype, _ in chunks]
        self.assertIn(b"IHDR", chunk_types)
        self.assertIn(b"IEND", chunk_types)
        self.assertNotIn(b"tEXt", chunk_types)
        self.assertNotIn(b"zTXt", chunk_types)
        self.assertNotIn(b"iTXt", chunk_types)

    def test_clean_does_not_modify_original_file(self) -> None:
        core.clean_file(self.png_path)
        self.assertEqual(sha256_of(self.png_path), self.original_hash)


# ---------------------------------------------------------------------------
# SPEC item 4: unrecognized format (.xyz random bytes)
# ---------------------------------------------------------------------------


class TestUnknownFormat(TempDirTestCase):
    def setUp(self) -> None:
        super().setUp()
        self.xyz_path = self.tmp_path / "mystery.xyz"
        write_random_bytes_file(self.xyz_path)
        self.original_hash = sha256_of(self.xyz_path)

    def test_scan_reports_unknown_kind_or_error(self) -> None:
        result = core.scan_file(self.xyz_path)
        self.assertTrue(
            result.kind == "unknown" or result.error is not None,
            f"expected kind=='unknown' or a populated error, got "
            f"kind={result.kind!r} error={result.error!r}",
        )

    def test_clean_fails_with_chinese_message_and_no_output(self) -> None:
        result = core.clean_file(self.xyz_path)
        self.assertFalse(result.ok)
        self.assertIsNone(result.output)
        self.assertTrue(result.message, "expected a human-readable message")
        self.assertNotIn("Traceback", result.message)
        # SPEC rule 3 quotes a specific message for this case: 「跳过：无法识别
        # 的文件格式」. We check its two key words rather than the full string
        # verbatim, to tolerate minor rewording while still holding the
        # implementation to the documented meaning (not just "any Chinese").
        self.assertIn("跳过", result.message)
        self.assertIn("无法识别", result.message)

    def test_clean_writes_no_new_files(self) -> None:
        core.clean_file(self.xyz_path)
        self.assertEqual(
            sorted(p.name for p in self.tmp_path.iterdir()),
            [self.xyz_path.name],
        )

    def test_clean_does_not_modify_original_file(self) -> None:
        core.clean_file(self.xyz_path)
        self.assertEqual(sha256_of(self.xyz_path), self.original_hash)


# ---------------------------------------------------------------------------
# SPEC item 5: default_output_path naming rules
# ---------------------------------------------------------------------------


class TestDefaultOutputPath(TempDirTestCase):
    def test_basic_suffix_no_collision(self) -> None:
        src = self.tmp_path / "photo.png"
        src.write_bytes(b"not-really-a-png")
        out = core.default_output_path(src)
        self.assertEqual(out.parent, src.parent)
        self.assertEqual(out.name, "photo_已清理.png")

    def test_collision_increments_suffix(self) -> None:
        src = self.tmp_path / "photo.png"
        src.write_bytes(b"not-really-a-png")

        (self.tmp_path / "photo_已清理.png").write_bytes(b"already exists")
        out2 = core.default_output_path(src)
        self.assertEqual(out2.name, "photo_已清理_2.png")

        (self.tmp_path / "photo_已清理_2.png").write_bytes(b"also already exists")
        out3 = core.default_output_path(src)
        self.assertEqual(out3.name, "photo_已清理_3.png")

    def test_out_dir_overrides_default_parent(self) -> None:
        src_dir = self.tmp_path / "sub"
        src_dir.mkdir()
        src = src_dir / "note.txt"
        src.write_text("hi", encoding="utf-8")

        out_dir = self.tmp_path / "elsewhere"
        out_dir.mkdir()

        out = core.default_output_path(src, out_dir=out_dir)
        self.assertEqual(out.parent, out_dir)
        self.assertEqual(out.name, "note_已清理.txt")

    def test_out_dir_none_defaults_to_source_directory(self) -> None:
        src = self.tmp_path / "doc.md"
        src.write_text("hi", encoding="utf-8")
        out = core.default_output_path(src, out_dir=None)
        self.assertEqual(out.parent, src.parent)
        self.assertEqual(out.name, "doc_已清理.md")


# ---------------------------------------------------------------------------
# SPEC item 6: original-file protection is exercised as part of every clean
# test above (TestZeroWidthMarkdown, TestCleanTextFile, TestPngTextChunk,
# TestUnknownFormat each assert the source file's hash is unchanged after a
# clean_file() call). No separate fixture is needed for this item.
# ---------------------------------------------------------------------------


if __name__ == "__main__":
    unittest.main()
